spring.application.name: social-run-app

management:
  endpoints.web.exposure.include: health,info
  endpoints.jmx.exposure.exclude: "*"

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true